### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by viditvarshney** [fossasia/susi_python#14]
Two Links are given in the footer section are not working. 
![susi](https://user-images.githubusercontent.com/34159717/74108795-b6fce180-4ba3-11ea-8da5-30045db68a99.PNG)

Two of the links, as shown in the image above, are not working: Overview and Blog

**Comment by norbusan** [comment]
This has nothing to do with `susi_python`, which is an API wrapper written in Python and not doing any frontend stuff. Please report to the proper project.

**Comment by viditvarshney** [comment]
@norbusan  Ohh! sorry team  I m little drunk last night, I will create this issue on the proper project. Thank you
